apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: njon
spec:
 replicas: 2
 selector:
  matchLabels:
   app: njon
 template:
  metadata:
   labels:
    app: njon
  spec:
   containers:
   - image: rejivl/rejikubia:latest
     name: njon
     ports:
     - containerPort: 8080
       protocol: TCP

